{\rtf1\ansi\ansicpg1252\cocoartf2761
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 Last login: Wed Aug 28 07:16:43 on ttys000\
davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % source .venv/bin/activate\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % python trainer.py\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-08-29 07:17:20.299534 -> 2024-08-28 07:17:20.299534) (Yahoo error = "1m data not available for startTime=1693307840 and endTime=1724843840. Only 7 days worth of 1m granularity data are allowed to be fetched per request.")')\
Training LSTM model:   0%|                                                                                      | 0/100 [00:00<?, ?it/s]\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-08-29 07:17:20.299534 -> 2024-08-28 07:17:20.299534) (Yahoo error = "1m data not available for startTime=1693307840 and endTime=1724843840. Only 7 days worth of 1m granularity data are allowed to be fetched per request.")')\
Training LSTM model:   0%|                                                                                      | 0/100 [00:00<?, ?it/s]\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-08-29 07:17:20.299534 -> 2024-08-28 07:17:20.299534) (Yahoo error = "1m data not available for startTime=1693307840 and endTime=1724843840. Only 7 days worth of 1m granularity data are allowed to be fetched per request.")')\
Training LSTM model:   0%|                                                                                      | 0/100 [00:00<?, ?it/s]\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-08-29 07:17:20.299534 -> 2024-08-28 07:17:20.299534) (Yahoo error = "1m data not available for startTime=1693307840 and endTime=1724843840. Only 7 days worth of 1m granularity data are allowed to be fetched per request.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-08-29 07:17:20.299534 -> 2024-08-28 07:17:20.299534) (Yahoo error = "1m data not available for startTime=1693307840 and endTime=1724843840. Only 7 days worth of 1m granularity data are allowed to be fetched per request.")')\
Training LSTM model:   0%|                                                                                      | 0/100 [00:00<?, ?it/s]\
Training LSTM model:   0%|                                                                                      | 0/100 [00:00<?, ?it/s]\
multiprocessing.pool.RemoteTraceback:\
"""\
Traceback (most recent call last):\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker\
    result = (True, func(*args, **kwds))\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar\
    return list(map(*args))\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 221, in process_stock\
    lstm_model = train_model(X, y, seq_length, lstm_params, lr, num_epochs, 'lstm')\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 151, in train_model\
    for seq, target in dataloader:\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 440, in __iter__\
    return self._get_iterator()\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator\
    return _MultiProcessingDataLoaderIter(self)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1038, in __init__\
    w.start()\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 118, in start\
    assert not _current_process._config.get('daemon'), \\\
AssertionError: daemonic processes are not allowed to have children\
"""\
\
The above exception was the direct cause of the following exception:\
\
Traceback (most recent call last):\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 245, in <module>\
    results = p.map(partial(process_stock, start_date=start_date, end_date=end_date,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 367, in map\
    return self._map_async(func, iterable, mapstar, chunksize).get()\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 774, in get\
    raise self._value\
AssertionError: daemonic processes are not allowed to have children\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown\
  warnings.warn('resource_tracker: There appear to be %d '\
\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % python trainer.py\
^CTraceback (most recent call last):\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 238, in <module>\
    get_data('AAPL', start_date, end_date)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 88, in get_data\
    bars = stock_client.get_stock_bars(request_params)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/alpaca/data/historical/stock.py", line 101, in get_stock_bars\
    raw_bars = self._data_get(\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/alpaca/data/historical/stock.py", line 347, in _data_get\
    response = self.get(path=path, data=params, api_version=api_version)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/alpaca/common/rest.py", line 221, in get\
    return self._request("GET", path, data, **kwargs)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/alpaca/common/rest.py", line 129, in _request\
    return self._one_request(method, url, opts, retry)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/alpaca/common/rest.py", line 193, in _one_request\
    response = self._session.request(method, url, **opts)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request\
    resp = self.send(prep, **send_kwargs)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/requests/sessions.py", line 746, in send\
    r.content\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/requests/models.py", line 902, in content\
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""\
KeyboardInterrupt\
\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % python trainer.py\
in get_data\
creating features\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-08-29 22:35:51.084086 -> 2024-08-28 22:35:51.084086) (Yahoo error = "1m data not available for startTime=1693362951 and endTime=1724898951. Only 7 days worth of 1m granularity data are allowed to be fetched per request.")')\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % python trainer.py\
in get_data\
creating features\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['SPY']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-08-29 22:36:24.488848 -> 2024-08-28 22:36:24.488848) (Yahoo error = "1m data not available for startTime=1693362984 and endTime=1724898984. Only 7 days worth of 1m granularity data are allowed to be fetched per request.")')\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % python trainer.py\
in get_data\
creating features\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-08-29 22:38:41.725979 -> 2023-09-05 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1693363121 and endTime=1693967921. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-09-05 22:38:41.725979 -> 2023-09-12 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1693967921 and endTime=1694572721. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-09-12 22:38:41.725979 -> 2023-09-19 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1694572721 and endTime=1695177521. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-09-19 22:38:41.725979 -> 2023-09-26 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1695177521 and endTime=1695782321. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-09-26 22:38:41.725979 -> 2023-10-03 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1695782321 and endTime=1696387121. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-10-03 22:38:41.725979 -> 2023-10-10 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1696387121 and endTime=1696991921. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-10-10 22:38:41.725979 -> 2023-10-17 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1696991921 and endTime=1697596721. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-10-17 22:38:41.725979 -> 2023-10-24 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1697596721 and endTime=1698201521. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-10-24 22:38:41.725979 -> 2023-10-31 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1698201521 and endTime=1698806321. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-10-31 22:38:41.725979 -> 2023-11-07 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1698806321 and endTime=1699414721. Only 7 days worth of 1m granularity data are allowed to be fetched per request.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-11-07 22:38:41.725979 -> 2023-11-14 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1699414721 and endTime=1700019521. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-11-14 22:38:41.725979 -> 2023-11-21 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1700019521 and endTime=1700624321. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-11-21 22:38:41.725979 -> 2023-11-28 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1700624321 and endTime=1701229121. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-11-28 22:38:41.725979 -> 2023-12-05 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1701229121 and endTime=1701833921. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-12-05 22:38:41.725979 -> 2023-12-12 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1701833921 and endTime=1702438721. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-12-12 22:38:41.725979 -> 2023-12-19 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1702438721 and endTime=1703043521. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-12-19 22:38:41.725979 -> 2023-12-26 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1703043521 and endTime=1703648321. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2023-12-26 22:38:41.725979 -> 2024-01-02 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1703648321 and endTime=1704253121. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-01-02 22:38:41.725979 -> 2024-01-09 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1704253121 and endTime=1704857921. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-01-09 22:38:41.725979 -> 2024-01-16 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1704857921 and endTime=1705462721. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-01-16 22:38:41.725979 -> 2024-01-23 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1705462721 and endTime=1706067521. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-01-23 22:38:41.725979 -> 2024-01-30 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1706067521 and endTime=1706672321. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-01-30 22:38:41.725979 -> 2024-02-06 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1706672321 and endTime=1707277121. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-02-06 22:38:41.725979 -> 2024-02-13 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1707277121 and endTime=1707881921. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-02-13 22:38:41.725979 -> 2024-02-20 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1707881921 and endTime=1708486721. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-02-20 22:38:41.725979 -> 2024-02-27 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1708486721 and endTime=1709091521. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-02-27 22:38:41.725979 -> 2024-03-05 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1709091521 and endTime=1709696321. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-03-05 22:38:41.725979 -> 2024-03-12 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1709696321 and endTime=1710297521. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-03-12 22:38:41.725979 -> 2024-03-19 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1710297521 and endTime=1710902321. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-03-19 22:38:41.725979 -> 2024-03-26 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1710902321 and endTime=1711507121. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-03-26 22:38:41.725979 -> 2024-04-02 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1711507121 and endTime=1712111921. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-04-02 22:38:41.725979 -> 2024-04-09 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1712111921 and endTime=1712716721. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-04-09 22:38:41.725979 -> 2024-04-16 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1712716721 and endTime=1713321521. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-04-16 22:38:41.725979 -> 2024-04-23 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1713321521 and endTime=1713926321. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-04-23 22:38:41.725979 -> 2024-04-30 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1713926321 and endTime=1714531121. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-04-30 22:38:41.725979 -> 2024-05-07 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1714531121 and endTime=1715135921. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-05-07 22:38:41.725979 -> 2024-05-14 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1715135921 and endTime=1715740721. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-05-14 22:38:41.725979 -> 2024-05-21 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1715740721 and endTime=1716345521. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-05-21 22:38:41.725979 -> 2024-05-28 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1716345521 and endTime=1716950321. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-05-28 22:38:41.725979 -> 2024-06-04 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1716950321 and endTime=1717555121. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-06-04 22:38:41.725979 -> 2024-06-11 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1717555121 and endTime=1718159921. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-06-11 22:38:41.725979 -> 2024-06-18 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1718159921 and endTime=1718764721. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-06-18 22:38:41.725979 -> 2024-06-25 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1718764721 and endTime=1719369521. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-06-25 22:38:41.725979 -> 2024-07-02 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1719369521 and endTime=1719974321. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-07-02 22:38:41.725979 -> 2024-07-09 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1719974321 and endTime=1720579121. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-07-09 22:38:41.725979 -> 2024-07-16 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1720579121 and endTime=1721183921. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-07-16 22:38:41.725979 -> 2024-07-23 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1721183921 and endTime=1721788721. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
\
1 Failed download:\
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1m 2024-07-23 22:38:41.725979 -> 2024-07-30 22:38:41.725979) (Yahoo error = "1m data not available for startTime=1721788721 and endTime=1722393521. The requested range must be within the last 30 days.")')\
[*********************100%***********************]  1 of 1 completed\
[*********************100%***********************]  1 of 1 completed\
[*********************100%***********************]  1 of 1 completed\
[*********************100%***********************]  1 of 1 completed\
[*********************100%***********************]  1 of 1 completed\
/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py:88: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.\
  return pd.concat(data_chunks)\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % python trainer.py\
in get_data\
creating features\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % python trainer.py\
Traceback (most recent call last):\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 253, in <module>\
    s#ymbols = ['AAPL', 'GOOGL', 'MSFT', 'AMZN', 'META']  # Stocks\
NameError: name 's' is not defined. Did you mean: 'os'?\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % python trainer.py\
in get_data\
creating features\
Training LSTM model:   0%|                                        | 0/100 [00:00<?, ?it/s]\
multiprocessing.pool.RemoteTraceback:\
"""\
Traceback (most recent call last):\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker\
    result = (True, func(*args, **kwds))\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar\
    return list(map(*args))\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 241, in process_stock\
    transformer_model = train_model(X, y, seq_length, transformer_params, lr, num_epochs, 'transformer')\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 171, in train_model\
    seq, target = seq.to(device), target.to(device)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 440, in __iter__\
    return self._get_iterator()\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator\
    return _MultiProcessingDataLoaderIter(self)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1038, in __init__\
    w.start()\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 118, in start\
    assert not _current_process._config.get('daemon'), \\\
AssertionError: daemonic processes are not allowed to have children\
"""\
\
The above exception was the direct cause of the following exception:\
\
Traceback (most recent call last):\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 267, in <module>\
    seq_length=seq_length, lstm_params=lstm_params,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 367, in map\
    return self._map_async(func, iterable, mapstar, chunksize).get()\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 774, in get\
    raise self._value\
AssertionError: daemonic processes are not allowed to have children\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown\
  warnings.warn('resource_tracker: There appear to be %d '\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % python trainer.py\
Training LSTM model:   0%|                                        | 0/100 [00:00<?, ?it/s]\
multiprocessing.pool.RemoteTraceback:\
"""\
Traceback (most recent call last):\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker\
    result = (True, func(*args, **kwds))\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar\
    return list(map(*args))\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 230, in process_stock\
    lstm_model = train_model(X, y, seq_length, lstm_params, lr, num_epochs, 'lstm')\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 160, in train_model\
    for seq, target in dataloader:\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 440, in __iter__\
    return self._get_iterator()\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator\
    return _MultiProcessingDataLoaderIter(self)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1038, in __init__\
    w.start()\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 118, in start\
    assert not _current_process._config.get('daemon'), \\\
AssertionError: daemonic processes are not allowed to have children\
"""\
\
The above exception was the direct cause of the following exception:\
\
Traceback (most recent call last):\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 258, in <module>\
    results = p.map(partial(process_stock, start_date=start_date, end_date=end_date,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 367, in map\
    return self._map_async(func, iterable, mapstar, chunksize).get()\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 774, in get\
    raise self._value\
AssertionError: daemonic processes are not allowed to have children\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown\
  warnings.warn('resource_tracker: There appear to be %d '\
python trainer.py\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again %\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % python trainer.py\
^CTraceback (most recent call last):\
  File "<string>", line 1, in <module>\
Traceback (most recent call last):\
Traceback (most recent call last):\
  File "<string>", line 1, in <module>\
  File "<string>", line 1, in <module>\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main\
Traceback (most recent call last):\
  File "<string>", line 1, in <module>\
    exitcode = _main(fd, parent_sentinel)\
    exitcode = _main(fd, parent_sentinel)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main\
Traceback (most recent call last):\
Traceback (most recent call last):\
  File "<string>", line 1, in <module>\
  File "<string>", line 1, in <module>\
    prepare(preparation_data)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare\
    prepare(preparation_data)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare\
    exitcode = _main(fd, parent_sentinel)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main\
Traceback (most recent call last):\
  File "<string>", line 1, in <module>\
    _fixup_main_from_path(data['init_main_from_path'])\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path\
    _fixup_main_from_path(data['init_main_from_path'])\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main\
Traceback (most recent call last):\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main\
  File "<string>", line 1, in <module>\
    exitcode = _main(fd, parent_sentinel)\
    main_content = runpy.run_path(main_path,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main\
    exitcode = _main(fd, parent_sentinel)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main\
    exitcode = _main(fd, parent_sentinel)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main\
    exitcode = _main(fd, parent_sentinel)\
    return _run_module_code(code, init_globals, run_name,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code\
    main_content = runpy.run_path(main_path,\
    prepare(preparation_data)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare\
    prepare(preparation_data)\
    prepare(preparation_data)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare\
    exitcode = _main(fd, parent_sentinel)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main\
    _fixup_main_from_path(data['init_main_from_path'])\
    _fixup_main_from_path(data['init_main_from_path'])\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path\
    return _run_module_code(code, init_globals, run_name,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code\
    _run_code(code, mod_globals, init_globals,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code\
    _run_code(code, mod_globals, init_globals,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code\
    main_content = runpy.run_path(main_path,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path\
    prepare(preparation_data)\
    _fixup_main_from_path(data['init_main_from_path'])\
    exec(code, run_globals)\
    prepare(preparation_data)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 3, in <module>\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main\
    exec(code, run_globals)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 3, in <module>\
    import torch\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/__init__.py", line 1718, in <module>\
    return _run_module_code(code, init_globals, run_name,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code\
    _fixup_main_from_path(data['init_main_from_path'])\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path\
    _run_code(code, mod_globals, init_globals,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code\
    import torch\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/__init__.py", line 1755, in <module>\
    prepare(preparation_data)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare\
    exec(code, run_globals)\
    main_content = runpy.run_path(main_path,\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 3, in <module>\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path\
    import torch\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/__init__.py", line 1755, in <module>\
    main_content = runpy.run_path(main_path,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path\
    _fixup_main_from_path(data['init_main_from_path'])\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path\
    if __name.startswith('__') or __name in PRIVATE_OPS:\
KeyboardInterrupt\
Traceback (most recent call last):\
  File "<string>", line 1, in <module>\
    return _run_module_code(code, init_globals, run_name,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main\
    from .functional import *  # noqa: F403\
    main_content = runpy.run_path(main_path,\
    main_content = runpy.run_path(main_path,\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/functional.py", line 10, in <module>\
    _run_code(code, mod_globals, init_globals,\
    return _run_module_code(code, init_globals, run_name,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path\
Traceback (most recent call last):\
  File "<string>", line 1, in <module>\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code\
    import torch.nn.functional as F\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/nn/__init__.py", line 2, in <module>\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main\
    _fixup_main_from_path(data['init_main_from_path'])\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path\
    return _run_module_code(code, init_globals, run_name,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code\
    exec(code, run_globals)\
    exitcode = _main(fd, parent_sentinel)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 3, in <module>\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main\
    main_content = runpy.run_path(main_path,\
    _run_code(code, mod_globals, init_globals,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code\
    _run_code(code, mod_globals, init_globals,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code\
    import torch\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/__init__.py", line 1755, in <module>\
    exitcode = _main(fd, parent_sentinel)\
    prepare(preparation_data)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare\
    exec(code, run_globals)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 3, in <module>\
    exec(code, run_globals)\
    return _run_module_code(code, init_globals, run_name,\
    import torch\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/__init__.py", line 1755, in <module>\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 3, in <module>\
    _fixup_main_from_path(data['init_main_from_path'])\
    from .functional import *  # noqa: F403\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/functional.py", line 10, in <module>\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path\
    from .modules import *  # noqa: F403\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 2, in <module>\
    _run_code(code, mod_globals, init_globals,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code\
    import torch.nn.functional as F\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/nn/__init__.py", line 2, in <module>\
    main_content = runpy.run_path(main_path,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path\
    prepare(preparation_data)\
    exec(code, run_globals)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 3, in <module>\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare\
    from .modules import *  # noqa: F403\
    import torch\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/__init__.py", line 1717, in <module>\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 20, in <module>\
    import torch\
    return _run_module_code(code, init_globals, run_name,\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/__init__.py", line 1755, in <module>\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code\
    return _run_module_code(code, init_globals, run_name,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code\
    _run_code(code, mod_globals, init_globals,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code\
    from .functional import *  # noqa: F403\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/functional.py", line 10, in <module>\
    import torch.nn.functional as F\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/nn/__init__.py", line 2, in <module>\
    exec(code, run_globals)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 3, in <module>\
    from .modules import *  # noqa: F403\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 2, in <module>\
    import torch\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/__init__.py", line 1755, in <module>\
    _run_code(code, mod_globals, init_globals,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code\
    from .instancenorm import InstanceNorm1d, InstanceNorm2d, InstanceNorm3d, \\\
    _fixup_main_from_path(data['init_main_from_path'])\
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path\
    exec(code, run_globals)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 3, in <module>\
    from .functional import *  # noqa: F403\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/functional.py", line 10, in <module>\
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\
    from .linear import Identity, Linear, Bilinear, LazyLinear\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 8, in <module>\
    from .linear import Identity, Linear, Bilinear, LazyLinear\
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 8, in <module>\
    from .functional import *  # noqa: F403\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/functional.py", line 10, in <module>\
    import torch\
    import torch.nn.functional as F\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/nn/__init__.py", line 2, in <module>\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/__init__.py", line 1755, in <module>\
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module\
    from .functional import *  # noqa: F403\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/functional.py", line 10, in <module>\
    from .modules import *  # noqa: F403\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 2, in <module>\
    import torch.nn.functional as F\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/nn/__init__.py", line 2, in <module>\
    import torch.nn.functional as F\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/nn/__init__.py", line 2, in <module>\
Traceback (most recent call last):\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 257, in <module>\
    results = p.map(partial(process_stock, start_date=start_date, end_date=end_date,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 367, in map\
    return self._map_async(func, iterable, mapstar, chunksize).get()\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 768, in get\
    self.wait(timeout)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 765, in wait\
    self._event.wait(timeout)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 607, in wait\
    signaled = self._cond.wait(timeout)\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 320, in wait\
    waiter.acquire()\
KeyboardInterrupt\
\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % python trainer.py\
multiprocessing.pool.RemoteTraceback:\
"""\
Traceback (most recent call last):\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker\
    result = (True, func(*args, **kwds))\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar\
    return list(map(*args))\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 228, in process_stock\
    X, y, scaler, data = get_data(symbol, start_date, end_date)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 127, in get_data\
    X = data[features].values\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 4108, in __getitem__\
    indexer = self.columns._get_indexer_strict(key, "columns")[1]\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict\
    self._raise_if_missing(keyarr, indexer, axis_name)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing\
    raise KeyError(f"\{not_found\} not in index")\
KeyError: "['log_returns', 'ma_10', 'ma_30', 'rsi', 'bb_high', 'bb_mid', 'bb_low', 'macd', 'atr', 'obv', 'cci', 'adx', 'sentiment'] not in index"\
"""\
\
The above exception was the direct cause of the following exception:\
\
Traceback (most recent call last):\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 257, in <module>\
    results = p.map(partial(process_stock, start_date=start_date, end_date=end_date,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 367, in map\
    return self._map_async(func, iterable, mapstar, chunksize).get()\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 774, in get\
    raise self._value\
KeyError: "['log_returns', 'ma_10', 'ma_30', 'rsi', 'bb_high', 'bb_mid', 'bb_low', 'macd', 'atr', 'obv', 'cci', 'adx', 'sentiment'] not in index"\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % python trainer.py\
Training LSTM model: 100%|\uc0\u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 | 100/100 [50:48<00:00, 30.49s/it, Loss=0.0000]\
/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py:307: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)\
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because \{why_not_sparsity_fast_path\}")\
Training TRANSFORMER model: 100%|\uc0\u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 \u9608 | 100/100 [2:59:25<00:00, 107.66s/it, Loss=0.0000]\
multiprocessing.pool.RemoteTraceback:\
"""\
Traceback (most recent call last):\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/alpaca/common/rest.py", line 196, in _one_request\
    response.raise_for_status()\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status\
    raise HTTPError(http_error_msg, response=self)\
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/orders\
\
During handling of the above exception, another exception occurred:\
\
Traceback (most recent call last):\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker\
    result = (True, func(*args, **kwds))\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar\
    return list(map(*args))\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 233, in process_stock\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 195, in trade\
    position = balance // data[i+60, 0]\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/alpaca/trading/client.py", line 98, in submit_order\
    response = self.post("/orders", data)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/alpaca/common/rest.py", line 236, in post\
    return self._request("POST", path, data)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/alpaca/common/rest.py", line 129, in _request\
    return self._one_request(method, url, opts, retry)\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/.venv/lib/python3.10/site-packages/alpaca/common/rest.py", line 205, in _one_request\
    raise APIError(error, http_error)\
alpaca.common.exceptions.APIError: \{"buying_power":"200000","code":40310000,"cost_basis":"5265141401.8","message":"insufficient buying power"\}\
"""\
\
The above exception was the direct cause of the following exception:\
\
Traceback (most recent call last):\
  File "/Users/davidmutascio/Desktop/enigmaTrainer_again/trainer.py", line 257, in <module>\
    seq_length=seq_length, lstm_params=lstm_params,\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 367, in map\
    return self._map_async(func, iterable, mapstar, chunksize).get()\
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 774, in get\
    raise self._value\
alpaca.common.exceptions.APIError: \{"buying_power":"200000","code":40310000,"cost_basis":"5265141401.8","message":"insufficient buying power"\}\
(.venv) davidmutascio@Davids-MacBook-Pro enigmaTrainer_again % /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown\
  warnings.warn('resource_tracker: There appear to be %d '\
}